version: '3'
networks:
  app-net:
    driver: bridge
services:
  frontend:
    image: laurkan/kanban-frontend:0.0.3
    build:
      context: ../
      args:
        REACT_APP_BACKEND_URL: "/api"
    container_name: frontend
    networks:
      - app-net
    stdin_open: true