version: '3'
networks:
  app-net:
    driver: bridge
services:
  frontend:
    image: laurkan/kanban-frontend:0.0.1
    build:
      context: ../
    container_name: frontend
    networks:
      - app-net
    stdin_open: true